os: 
 "linux"
 "windows"

language: c

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- if [[$TRAVIS_COMMIT_MSG =~ "DevDC1"]]; then $TRAVIS_OS_NAME = "windows"; fi
- if [[$TRAVIS_COMMIT_MSG =~ "02L"]]; then $TRAVIS_OS_NAME = "linux"; fi

  
addons:
  apt:
    packages:
    - libc6-i386 
    
    

install:
- if [[$TRAVIS_COMMIT_MSG =~ "DevDC1"]]; then ./batch.bat; fi
- if [[$TRAVIS_COMMIT_MSG =~ "02L"]]; then ./deploy.sh; fi
- pwd

script: 
  - chmod +x deploy.sh
  - ./deploy.sh
  
after_deploy: 
  - ls
  
