os: 
 "linux"
dist:
 "focal"
language: python
node_js:
- "3.6"
- "pypy3" 
before_install:
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com

install:
 - pip install sh

script: deploy.sh
  
after_success: echo "Success"
