os: 
 #- windows
 - linux

language: cpp

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi
    
install:
- pwd
#- pushd /c/Users/travis/build/ && mkdir arm-gcc && cd arm-gcc
- curl -fL https://getcli.jfrog.io | sh
#- cp /c/Users/travis/build/rajitha1908/GitAWS/folder1.zip ${PWD}
- jar xf folder1.zip
- export PATH="$PATH:${PWD}"
- ls
#- popd
#- capicom.dll --version



script: 
- pwd
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat; fi
- chmod +x deploy.sh
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy.sh; fi

  
after_success: 
- echo "deployed"
 