language: node_js
node_js:
- "8.11"
before_install:
- echo "new file"
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
deploy:
 provider: script
 script: 
 - echo. "deployed"
after_success: echo "Success!"
