os: 
 - windows

language: cpp

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
- curl -fL https://getcli.jfrog.io | sh
    
install:
- pushd /c/Users/travis/build/ && mkdir arm-gcc && cd arm-gcc
- curl -fL https://getcli.jfrog.io | sh
- popd


script: 
- pwd
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat; fi
#- chmod +x deploy.sh
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy.sh; fi

  
after_success: 
- echo "deployed"
 