os: 
 "linux"
dist:
 "focal"
language: c

before_install:
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
  
jobs:
  include:
    compiler: 
     - clang
     - gcc
install:
  
  - export PATH=$HOME/arm-gcc-toolchain/bin:$PATH
  - pwd
  

script: 
  - chmod +x deploy.sh
  - ./deploy.sh
  
after_deploy: 
  - ls
  
