os: 
 "linux"
dist:
 "focal"
language: python
node_js:
- "3.6"
before_install:
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com

install:
 - pip install sh

script:
 if [[ $TRAVIS_TAG ]]; then 
    ./deploy.sh;
 fi
 
  
after_success: echo "Success"
