os: 
 - linux

language: c

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "$TRAVIS_OS_NAME"

install:
- pwd

script:
  - chmod +x deploy.sh
  - ./deploy.sh

deploy: 
  skip_cleanup : true
  
after_deploy: 
- ls
  
