os: 
 #- windows
 - linux

language: cpp

before_install: 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
- sudo apt-get install qtchooser g++-4.8 
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

#env:
    #- QT_CI_PACKAGES=qt.qt5.5120.gcc_64,qt.qt5.5120.qtwebengine PATH="/home/travis/build/Qt/5.12.0/gcc_64/bin:${PATH}"
  
install:
- pwd
- pushd /home/travis/build/ && mkdir arm-gcc && cd arm-gcc
- sudo wget -q "https://download.qt.io/official_releases/qt/5.12/5.12.10/qt-opensource-linux-x64-5.12.10.run"
- qtchooser -install 5120 /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
- ls
- qmake --version
- cd ..
- export PATH="$PATH:${PWD}/arm-gcc"
- ls 
- popd
- qmake --version
- make --version
- qmake-qt5 --version

script: 
- pwd
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat; fi
- chmod +x deploy.sh
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy.sh; fi

  
after_success: 
- echo "deployed"
 