os: 
 "linux"
dist:
 "focal"
language: c

before_install:
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
  

addons:
  apt:
    packages:
    - libc6-i386 
    cache:
  pip: true
  ccache: true
  # It looks like ccache for arm-none-eabi is not yet supported by Travis.
  # Therefore manually adding ccache directory to cache
  directories:
    - ${HOME}/.ccache


install:
  - ccache -o compiler_check=content
  - ccache -M 1G
  - pushd /usr/lib/ccache
  - sudo ln -s ../../bin/ccache arm-none-eabi-gcc
  - sudo ln -s ../../bin/ccache arm-none-eabi-g++
  - export PATH="/usr/lib/ccache:$PATH"
  - popd
  # Install arm-none-eabi-gcc
  - pushd /home/travis/build && mkdir arm-gcc && cd arm-gcc
  - curl -L0 "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2?revision=05382cca-1721-44e1-ae19-1e7c3dc96118&la=en&hash=D7C9D18FCA2DD9F894FD9F3C3DC9228498FA281A" --output gcc-arm-none-eabi-9-2020-q2-update.tar.bz2
  - tar xf gcc-arm-none-eabi-9-2020-q2-update.tar.bz2
  - export PATH="$PATH:${PWD}/gcc-arm-none-eabi-9-2020-q2-update/bin"
  - popd
  - arm-none-eabi-gcc --version

script: 
  - chmod +x deploy.sh
  - ./deploy.sh
  
after_deploy: 
  - ls
  
