os: 
 #- windows
 - linux

language: cpp

before_install: 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
- sudo apt-get install --force-yes -qq p7zip  #lib32* are needed by Android SDK

#- sudo apt-get install qtchooser g++-4.8 qt5-qmake make
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
#- sudo update-alternatives --config qmake
#- sudo update-alternatives --install /usr/bin/qmake qmake /usr/lib/x86_64-linux-gnu/qt5/bin/qmake 100


#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

#env:
    #- QT_CI_PACKAGES=qt.qt5.5120.gcc_64,qt.qt5.5120.qtwebengine PATH="/home/travis/build/Qt/5.12.0/gcc_64/bin:${PATH}"
  
install:
- pwd
- pushd /home/travis/build/ && mkdir arm-gcc && cd arm-gcc
- wget -c https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
#- extract-qt-installer --list-packages qt-unified-linux-x64-online.run
- sudo install-qt-5.12.0
- ls
- qmake --version
- cd ..
- export PATH="$PATH:${PWD}/arm-gcc"
- ls 
- popd
- qmake --version
- make --version

script: 
- pwd
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat; fi
- chmod +x deploy.sh
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy.sh; fi

  
after_success: 
- echo "deployed"
 