os: 
 - windows

language: cpp

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
    
install:
- pushd /c/Users/travis/build/ && mkdir arm-gcc && cd arm-gcc
- curl http://www.microsoft.com/en-us/download/details.aspx?id=25281 --output capicom.dll
#- regsvr32 capicom.dll
- export PATH="$PATH:${PWD}/capicom.dll"
- curl -fL https://getcli.jfrog.io | sh
- cp /c/Users/travis/build/rajitha1908/GitAWS/folder1.zip ${PWD}
- 7z x folder1.zip
- ls
- echo "capicom.dll --version"
- popd
- capicom.dll --version



script: 
- pwd
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat; fi
#- chmod +x deploy.sh
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./deploy.sh; fi

  
after_success: 
- echo "deployed"
 