os: 
 "linux"
 "windows"
dist:
 "xenial"
language: cpp

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
    
install:
- pwd

script: 
 - pwd
 - ./build.bat
  
after_success: 
- echo "deployed"
 