os: 
 "linux"
dist:
 "focal"
language: python
node_js:
- "3.6"
before_install:
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com

install:
 - pip install sh
 
#if: branch = master OR tag IS present
if [ $(git tag -l "$version") ]; then
    echo yes
else
    echo no
fi

script:
 - chmod +x deploy.sh $TRAVIS_TAG
  
after_success: echo "Success"
