os: 
 "linux"
dist:
 "focal"
language: c

before_install:
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
  
jobs:
  include:
    - name: 9-2020-q2
      env: GCC_URL= https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2?revision=ca0cbf9c-9de2-491c-ac48-898b5bbc0443&la=en&hash=68760A8AE66026BCF99F05AC017A6A50C6FD832A
    
install:
  - pwd
  - pushd .
  - cd ~ 
  - mkdir arm-gcc-toolchain
  - wget -O $HOME/arm-gcc-toolchain $GCC_URL
  - cd arm-gcc-toolchain
  - tar -jxf gcc.tar.bz2 --strip=1
  - popd
  - export PATH=$HOME/arm-gcc-toolchain/bin:$PATH
  - pwd
  

script: 
  - chmod +x deploy.sh
  - ./deploy.sh
  
after_deploy: 
  - ls
  
