os: 
 "linux"
dist:
 "focal"
language: c

before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- echo "$TRAVIS_COMMIT_MSG" 
- git config --global user.name rajitha1905
- git config --global user.email rajitha.siripurapu@gmail.com
- echo "${PWD}"
    
install:
- pwd
- mkdir tool && cd tool
- cp /home/travis/build/rajitha1908/GitAWS/toolchain ${PWD}
- ls ${PWD}

script: 
 - pwd
 - cd toolchain
 - chmod -R +x ${PWD}/
 - ./newone.txt
 - ./deploy.sh
  
after_success: 
  - ls